apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gustavo/desafio-kubernetes:minikube
        ports:
        - containerPort: 3000
        env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: NAME
